# Exported from Render on 2024-10-27T23:44:59Z
services:
- type: web
  name: stat-site
  runtime: static
  repo: https://github.com/AIAssistantDeveloper/stat-site
  envVars:
  - key: DATABASE_URL
    value: postgresql://tony:DHbRYytyYGPgXKaHkqY97RXs5ORk8LRB@dpg-csf8h9tsvqrc73fckda0-a/contact_db_jb19
    sync: true
  buildCommand: gunicorn -w 4 -b 0.0.0.0:8000 app:app
  staticPublishPath: ./
version: "1"
